name: Build and release application

on:

  push:
    tags:        
      - v1.**
#  push:
#    branches:
#      - main
#      - 'releases/v**'

jobs:
  build:
    name: Build the app
    runs-on: windows-latest
    environment: Gitlab

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: test script
      uses: actions/github-script@v6
      with:
        script: |
            console.log('test test');
            console.log(process.env.GITHUB_REF);
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      working-directory: src/VoicemodPowertools
      run: dotnet restore
    
    - name: Build
      working-directory: src/VoicemodPowertools
      #run: dotnet build -c release --no-restore
      run: dotnet build -c Release -p:PublishProfile="./run/Publish FrameworkDependent.run.xml"
      
    - name: Set version
      id: set_version
      run: |
        cd src/VoicemodPowertools/bin/release/net6.0/
        dir
        src/VoicemodPowertools/bin/release/net6.0/voicemod-pow.exe --set-secrets clientId=${{ secrets.GITLABAPPLICATIONID }} clientSecret=${{ secrets.GITLABAPPLICATIONSECRET }} projectId=${{ secrets.GITLABVOICEMODDESKTOPPID }} --version=${{ github.ref }} --ignore-sec close
        dir

    - name: ts
      run: dir "src/VoicemodPowertools/bin/release/net6.0/"
      shell: powershell
    
    - uses: papeloto/action-zip@v1
      if: steps.set_version.outcome == 'success'
      with:
        files: src/VoicemodPowertools/bin/release/net6.0/
        recursive: true
        dest: VoicemodPowertools.zip

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./VoicemodPowertools.zip
        asset_name: VoicemodPowertools.zip
        asset_content_type: application/zip

