name: Build and release application

on:
  push:
    branches:
      - main
      - 'releases/v**'

jobs:
  build:
    name: Build the app
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: test script
      uses: actions/github-script@v6
      with:
        script: |
            console.log('test test');
            console.log(process.env.GITHUB_REF);
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      working-directory: src/VoicemodPowertools
      run: dotnet restore
    
    - name: Build
      working-directory: src/VoicemodPowertools
      run: dotnet build -c release --no-restore
      
    - uses: papeloto/action-zip@v1
      with:
        files: src/VoicemodPowertools/bin/release/net6.0/
        recursive: false
        dest: result.zip
      
    #- name: Upload a Build Artifact
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: VoicemodPowertools #.zip will be added automatically
    #    path: src/VoicemodPowertools/bin/release/net6.0/*.*

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: v.1.0.10 #${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./
        asset_name: result.zip
        asset_content_type: application/zip

